### ISSUE TITLE
Why are .lib, .exp and .pdb included? 

### ISSUE THREAD

**Issue by BoyBaykiller** [milleniumbug/NativeFileDialogSharp#4]
For windows, this project copies .lib, .exp and .pdb files of the native file dialog into the output directory of the host project. Why is this done?
I am pretty sure only the dll is needed in this case.

**Comment by milleniumbug** [comment]
It's been a while, but I don't think there's a specific reason why they're _included_, it was most likely me copying what was generated from the build of the native project and not deciding to _exclude_ unnecessary parts.

Looking at it once more, I estimate that .lib, .exp are definitely not necessary, though I am not sure if .pdb is, it's debug symbols for the native library.

**Comment by BoyBaykiller** [comment]
Alright.
Is there any chance we could exclude those files and update the nuget package?
In case you want to include debug symbols: I've never done that but I found out about `<DebugType>embedded</DebugType>`and [symbol package](https://learn.microsoft.com/de-de/nuget/create-packages/symbol-packages-snupkg) which might be of interest, but tbh I think its fine to not include them. I dont see any of the other bindings I use doing it.
